export const format = [
  { id: 1, label: "APA", value: "apa" },
  { id: 2, label: "MLP", value: "mlp" },
  { id: 3, label: "Chicago/Turabian", value: "chicago turabian" },
  { id: 4, label: "Harvard", value: "harvard" },
  { id: 5, label: "Other", value: "other" },
];

export const exam_types = [
  { id: 1, label: "Critical thinking", value: "critical thinking" },
  { id: 2, label: "Article review", value: "article review" },
  { id: 3, label: "Reflective report", value: "reflective report" },
  { id: 4, label: "Annotated bibliography", value: "annotated bibliography" },
  { id: 5, label: "Research proposal", value: "research proposal" },
  { id: 6, label: "Argumentative essay", value: "argumentative essay" },
  { id: 7, label: "Term paper", value: "term paper" },
  { id: 8, label: "Capstone project", value: "capstone project" },
  { id: 9, label: "Dissertation", value: "dissertation" },
  { id: 10, label: "Creative writing", value: "creative writing" },
  { id: 11, label: "Personal statement", value: "personal statement" },
  { id: 12, label: "Business plan", value: "business plan" },
  { id: 13, label: "Book review", value: "book review" },
  { id: 14, label: "Presentation", value: "presentation" },
  { id: 15, label: "Movie review", value: "movie review" },
  { id: 16, label: "Thesis", value: "thesis" },
  { id: 17, label: "Speech", value: "speech" },
  { id: 18, label: "Admission essay", value: "admission essay" },
  { id: 19, label: "Poster presentation", value: "poster presentation" },
  { id: 20, label: "Dissertation chapter", value: "dissertation chapter" },
  { id: 21, label: "Article", value: "article" },
  { id: 22, label: "Blog writing", value: "blog writing" },
  { id: 23, label: "Dissertation proposal", value: "dissertation proposal" },
  { id: 24, label: "Thesis proposal", value: "thesis proposal" },
  { id: 25, label: "Thesis statement", value: "thesis statement" },
  { id: 26, label: "Resume", value: "resume" },
  { id: 27, label: "Rewriting", value: "rewriting" },
  {
    id: 28,
    label: "Online Lecture to Summary",
    value: "online lecture to summary",
  },
  { id: 29, label: "Dissertation results", value: "dissertation results" },
  {
    id: 30,
    label: "Dissertation methodology",
    value: "dissertation methodology",
  },
  { id: 31, label: "Exam notes", value: "exam notes" },
  { id: 32, label: "Biography", value: "biography" },
  { id: 33, label: "Cover letter", value: "cover letter" },
  {
    id: 34,
    label: "Dissertation introduction",
    value: "dissertation introduction",
  },
  {
    id: 35,
    label: "Multiple choice questions",
    value: "multiple choice questions",
  },
  {
    id: 36,
    label: "Dissertation conclusion",
    value: "dissertation conclusion",
  },
  { id: 37, label: "Dissertation topics", value: "dissertation topics" },
  { id: 38, label: "Dissertation abstract", value: "dissertation abstract" },
  { id: 39, label: "Typing", value: "typing" },
  { id: 40, label: "Application letter", value: "application letter" },
  { id: 41, label: "Curriculum vitae", value: "curriculum vitae" },
  {
    id: 42,
    label: "Dissertation hypothesis",
    value: "dissertation hypothesis",
  },
  { id: 43, label: "Other", value: "other" },
];

export const subjects = [
  { id: 1, label: "Accounting", value: "accounting" },
  { id: 2, label: "Advertising", value: "advertising" },
  {
    id: 3,
    label: "Anthropology Art & architecture",
    value: "anthropology art & architecture",
  },
  { id: 4, label: "Astronomy", value: "astronomy" },
  { id: 5, label: "Aviation", value: "aviation" },
  { id: 6, label: "Biology", value: "biology" },
  { id: 7, label: "Business", value: "business" },
  { id: 8, label: "Chemistry", value: "chemistry" },
  {
    id: 9,
    label: "Classis English literature",
    value: "classis english literature",
  },
  { id: 10, label: "Communication", value: "communication" },
  { id: 11, label: "Computer Science", value: "computer science" },
  { id: 12, label: "Criminal Justice", value: "criminal justice" },
  { id: 13, label: "Criminal Law", value: "criminal law" },
  {
    id: 14,
    label: "Culture and Ethnic Studies",
    value: "culture and ethnic studies",
  },
  { id: 15, label: "Design", value: "design" },
  { id: 16, label: "Economics", value: "economics" },
  { id: 17, label: "Ecology", value: "ecology" },
  { id: 18, label: "Education", value: "education" },
  { id: 19, label: "Engineering", value: "engineering" },
  { id: 20, label: "English", value: "english" },
  { id: 21, label: "Environmental studies", value: "environmental studies" },
  { id: 22, label: "Ethics", value: "ethics" },
  {
    id: 23,
    label: "Family and consumer science",
    value: "family and consumer science",
  },
  { id: 24, label: "Film studies", value: "film studies" },
  { id: 25, label: "Finance", value: "finance" },
  { id: 26, label: "Financial Management", value: "financial management" },
  { id: 27, label: "Geology", value: "geology" },
  { id: 28, label: "Geography", value: "geography" },
  { id: 29, label: "Government", value: "government" },
  { id: 30, label: "Health Care", value: "health care" },
  { id: 31, label: "History", value: "history" },
  { id: 32, label: "Homeland Security", value: "homeland security" },
  {
    id: 33,
    label: "Human Resource Management",
    value: "human resource management",
  },
  { id: 34, label: "Human Services", value: "human services" },
  { id: 35, label: "Humanities", value: "humanities" },
  { id: 36, label: "Investments", value: "investments" },
  { id: 37, label: "Journalism", value: "journalism" },
  { id: 38, label: "Law", value: "law" },
  { id: 39, label: "Leadership", value: "leadership" },
  { id: 40, label: "Linguistics", value: "linguistics" },
  { id: 41, label: "Literature", value: "literature" },
  { id: 42, label: "Logic", value: "logic" },
  { id: 43, label: "Logistics", value: "logistics" },
  { id: 44, label: "Management", value: "management" },
  { id: 45, label: "Marketing", value: "marketing" },
  { id: 46, label: "Mathematics", value: "mathematics" },
  { id: 47, label: "Media", value: "media" },
  { id: 48, label: "Medicine", value: "medicine" },
  { id: 49, label: "Military science", value: "military science" },
  { id: 50, label: "Music", value: "music" },
  { id: 51, label: "Nursing", value: "nursing" },
  { id: 52, label: "Nutrition", value: "nutrition" },
  { id: 53, label: "Pharmacology", value: "pharmacology" },
  { id: 54, label: "Philosophy", value: "philosophy" },
  { id: 55, label: "Physics", value: "physics" },
  { id: 56, label: "Poetry", value: "poetry" },
  { id: 57, label: "Political science", value: "political science" },
  { id: 58, label: "Programming", value: "programming" },
  { id: 59, label: "Project Management", value: "project management" },
  { id: 60, label: "Psychology", value: "psychology" },
  { id: 61, label: "Public administration", value: "public administration" },
  { id: 62, label: "Public health", value: "public health" },
  { id: 63, label: "Religious studies", value: "religious studies" },
  { id: 64, label: "Risk Management", value: "risk management" },
  { id: 65, label: "Science", value: "science" },
  { id: 66, label: "Shakespeare studies", value: "shakespeare studies" },
  { id: 67, label: "Social Work", value: "social work" },
  { id: 68, label: "Sociology", value: "sociology" },
  { id: 69, label: "Sports", value: "sports" },
  { id: 70, label: "Statistics", value: "statistics" },
  {
    id: 71,
    label: "Supply Chain Management",
    value: "supply chain management",
  },
  { id: 72, label: "Technology", value: "technology" },
  { id: 73, label: "Theater studies", value: "theater studies" },
  { id: 74, label: "Theology", value: "theology" },
  { id: 75, label: "Tourism", value: "tourism" },
  {
    id: 76,
    label: "Women and gender studies",
    value: "women and gender studies",
  },
  { id: 77, label: "World affairs", value: "world affairs" },
  { id: 78, label: "World literature", value: "world literature" },
  { id: 79, label: "Other", value: "other" },
];
