"use client";
import { FC, ReactNode, useState, useCallback, useEffect } from "react"; // Added useEffect
// import AppNav from "./components/NavBar/AppNav";
import AppNav from "./components/LandingPage/Header";
import Footer from "./components/Footer/Footer";
import type { Metadata } from "next";
import AuthProvider from "./context/auth/AuthProvider";
import ExitPopUp from "./components/PopUpModal/ExitPopup";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "ScholarlyHelp",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  const pathname = usePathname();
  
  // Routes where header and footer should be hidden
  const hideHeaderFooterRoutes = [
    '/take-my-class',
    '/take-my-class/',
    '/take-my-class-1',
    '/take-my-class-1/',
    '/take-my-class-2',
    '/take-my-class-2/',
    '/take-my-exam',
    '/take-my-exam/',
  ];
  
  const shouldHideHeaderFooter = hideHeaderFooterRoutes.includes(pathname || '');

  // const [openExitPopup, setOpenExitPopup] = useState<boolean>(false);
  // const [userInteracted, setUserInteracted] = useState<boolean>(false);

  // // Auto-close popup after 30 seconds
  // useEffect(() => {
  //   let timer: NodeJS.Timeout;
  //   if (openExitPopup) {
  //     timer = setTimeout(() => {
  //       setOpenExitPopup(false);
  //     }, 30000); // 30 seconds
  //   }
  //   return () => clearTimeout(timer); // Cleanup on unmount or popup close
  // }, [openExitPopup]);

  // const handleUserInteraction = useCallback(() => {
  //   if (!userInteracted) setUserInteracted(true);
  // }, [userInteracted]);

  // const handleMouseLeave = (event: React.MouseEvent<HTMLDivElement>) => {
  //   if (event.clientY <= 0 && !userInteracted) {
  //     setOpenExitPopup(true);
  //   }
  // };

  return (
    <AuthProvider>
      {/* <div
        onClick={handleUserInteraction}
        onInput={handleUserInteraction}
        onMouseLeave={handleMouseLeave}
      > */}
      {!shouldHideHeaderFooter && <AppNav />}
      {children}
      {!shouldHideHeaderFooter && <Footer />}
      {/* <ExitPopUp
          open={openExitPopup}
          handleClose={() => setOpenExitPopup(false)}
        />
      </div> */}
    </AuthProvider>
  );
};

export default MainLayout;
