"use client";
import { FC, ReactNode, useState, useCallback, useEffect } from "react"; // Added useEffect
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";

// Lazy load auth provider
const AuthProvider = dynamic(() => import("./context/auth/AuthProvider"), {
  ssr: false,
});

// Lazy load header and footer to reduce initial bundle
const AppNav = dynamic(() => import("./components/LandingPage/Header"), {
  ssr: true,
});

const Footer = dynamic(() => import("./components/Footer/Footer"), {
  ssr: true,
});

const ExitPopUp = dynamic(() => import("./components/PopUpModal/ExitPopup"), {
  ssr: false,
});

const CookieBanner = dynamic(() => import("./components/CookieConsent"), {
  ssr: false,
});

const WhatsApp = dynamic(() => import("./components/WhatsApp/WhatsApp"), {
  ssr: false,
});



export const metadata: Metadata = {
  title: "ScholarlyHelp",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  const pathname = usePathname();
  
  // Routes where header and footer should be hidden
  const hideHeaderFooterRoutes = [
    '/take-my-class',
    '/take-my-class/',
    '/take-my-class-1',
    '/take-my-class-1/',
    '/take-my-class-2',
    '/take-my-class-2/',
    '/take-my-exam',
    '/take-my-exam/',
  ];
  
  const shouldHideHeaderFooter = hideHeaderFooterRoutes.includes(pathname || '');

  // const [openExitPopup, setOpenExitPopup] = useState<boolean>(false);
  // const [userInteracted, setUserInteracted] = useState<boolean>(false);

  // // Auto-close popup after 30 seconds
  // useEffect(() => {
  //   let timer: NodeJS.Timeout;
  //   if (openExitPopup) {
  //     timer = setTimeout(() => {
  //       setOpenExitPopup(false);
  //     }, 30000); // 30 seconds
  //   }
  //   return () => clearTimeout(timer); // Cleanup on unmount or popup close
  // }, [openExitPopup]);

  // const handleUserInteraction = useCallback(() => {
  //   if (!userInteracted) setUserInteracted(true);
  // }, [userInteracted]);

  // const handleMouseLeave = (event: React.MouseEvent<HTMLDivElement>) => {
  //   if (event.clientY <= 0 && !userInteracted) {
  //     setOpenExitPopup(true);
  //   }
  // };

  return (
    <AuthProvider>
      {/* <div
        onClick={handleUserInteraction}
        onInput={handleUserInteraction}
        onMouseLeave={handleMouseLeave}
      > */}
       <AppNav />
      {children}
      {!shouldHideHeaderFooter && <Footer />}
      <WhatsApp />
      <CookieBanner />
      {/* <ExitPopUp
          open={openExitPopup}
          handleClose={() => setOpenExitPopup(false)}
        />
      </div> */}
    </AuthProvider>
  );
};

export default MainLayout;
